### ISSUE TITLE
Update modules in make file and use specific revision for dev one

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#107]
We should stop using `1.x-dev` versions, as they may change from build to build.

**Comment by HelenaEksler** [comment]
There are 2 modules with `-dev` version: message subscribe and restful. 
I wouldn't change message subscribe version, cause the last update of the stable version was on 2014-Mar-30 (https://www.drupal.org/project/message_subscribe).
And restful version I think we can go to `1.0` version since it was updated on 2015-Apr-14 (https://www.drupal.org/project/restful).

**Comment by amitaibu** [comment]
no need to change to stable - but need to "lock" the [revision](https://github.com/openscholar/openscholar/blob/SCHOLAR-3.x/openscholar/drupal-org.make#L19)
