### ISSUE TITLE
[Frontend] Multiple calls to pusher auth

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#266]
(multiple as in 100+, more than the user is subscribed to I think)
Maybe all repos IDs are being sent to the client by mistake?

![https___app_shoov_io___repos_6101-3](https://cloud.githubusercontent.com/assets/125707/10867833/6e596cf2-8080-11e5-8e2a-8b79ca3ebc61.jpg)

**Comment by HelenaEksler** [comment]
@amitaibu I can't reproduce locally with the test data. Maybe you could send me the dump?

**Comment by amitaibu** [comment]
I think you have the dev dump I've sent you some time ago.

**Comment by HelenaEksler** [comment]
Locally I see that each time when I'm reloading page - the user is getting not from cache but from the backend, which is causing requests to Pusher since account when it's getting from the backend should be subscribed to all repo-channels he is member of.
https://github.com/shoov/shoov/blob/master/client/app/scripts/services/account.js#L25

**Comment by amitaibu** [comment]
works as designed
